git:
  depth: 1
dist: trusty
sudo: false
language: cpp
matrix:
  include:
    - os: linux
      language: generic
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - ninja-build
            - qtbase5-dev
            - qtbase5-dev-tools
            - qtdeclarative5-dev
            - qt5-qmake
      env:
        - COMPILER=g++ CXX=g++-5 CC=gcc-5
        - QT_PREFIX=/usr/lib/x86_64-linux-gnu/qt5
        - APPDIR=DwarfTherapist.AppDir
        - CMAKE_OPTIONS="-DCMAKE_INSTALL_PREFIX=$APPDIR/usr"
        - RELEASE_FILE='DwarfTherapist-*.AppImage'
    - os: osx
      before_install:
        - brew update
        - brew install qt@5.5
        - brew outdated cmake || brew upgrade cmake
        - brew install ninja
      env:
        - CXXFLAGS="$CXXFLAGS -mmacosx-version-min=10.9"
        - QT_PREFIX=/usr/local/opt/qt@5.5
        - CMAKE_PREFIX_PATH=$QT_PREFIX
        - RELEASE_FILE='DwarfTherapist-*.dmg'
env:
  global:
    - CXXFLAGS="-Wall -Wextra -Werror=all"
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export NPROC=$(nproc);
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then export NPROC=$(sysctl -n hw.ncpu);
    else export NPROC=1; fi
  - cmake -GNinja ${CMAKE_OPTIONS} . && ninja -j $NPROC -k 0
before_deploy:
  - ".travis/deploy.sh"
  - ".travis/$TRAVIS_OS_NAME/deploy.sh"
deploy:
  provider: releases
  api_key:
    secure: Oz4geKwd0UrXujKxr8z1y+qG88S+DZ6ifyOcbEsiaPoEpEO6uBZO8e7KRVIg9Yy55UTGTtchPjMHToZEtvCkMWSaJTq/zbLmaAEoBeEtJJ0xqaeew4LKhJof1Ld8U2LGCxobnKpbsPfB/AY88SCUgPf6avtB9rEFhgy77fdbVixsMFYcJpHQQTZslXPai9k19nFLtJL6h2HvhAf74ddNR0swUPBOvEZsiLq7fRb01LFCezuLurreVKIaD8OngJLVut+Ebqccfg5IuvZyNNOgLjlINocEZN3RRrxZz1lEMw6R7R/7QfSLCpSQx0eoBDqN/9L5pu+kJviop/Kfs50sQVQAigTlt8jslNbqLuXqnbijJxr512/TTxvzjuEdTe5EdQ8DIFQ+yJNdtlRPeqaHzWr+YMZqF646hv/9Fu9q9RnE+Xnoy7If1Gr4oq/uTbT8XbPNaw3vV+P9kOv/nX1ciUYvPwKtWZMG9rl2Pa0Ku7pNupsa9HEhbnxYr99L/qWMXb/YKOs2S2CIhqzq0EwpQd9EnzfhK7zjQnCv0OnLV/oWRz+MNlLpHviPi2xv88prOBFbKXMqHS3cPA5HNrSXzGFwh/ipg1g5BpRasohP716sYsE+2rEVnGyAM7N6oWUXO8K06D+tiQm46F2oyt85JMfqjzvcRCQQs7P1T/421Is=
  file_glob: true
  file: $RELEASE_FILE
  skip_cleanup: true
  on:
    repo: cvuchener/Dwarf-Therapist
    branch: deploy-test
