git:
  depth: 1
dist: xenial
sudo: true
language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:beineri/opt-qt-5.12.7-xenial'
          packages:
            - g++
            - cmake
            - ninja-build
            - qt512base
            - qt512declarative
            - qt512tools
            - mesa-common-dev
            - libglu1-mesa-dev
      env:
        - CXXFLAGS="-Wall -Wextra -Werror=all"
        - CMAKE_GENERATOR=Ninja
        - QT_PREFIX=/opt/qt512
        - APPDIR=DwarfTherapist.AppDir
        - CMAKE_OPTIONS="-GNinja -DCMAKE_INSTALL_PREFIX=$APPDIR/usr"
        - RELEASE_FILE='DwarfTherapist-*.AppImage'
    - os: osx
      env:
        - CXXFLAGS="-Wall -Wextra -Werror=all -mmacosx-version-min=10.9"
        - CMAKE_GENERATOR=Ninja
        - QT_PREFIX=/usr/local/opt/qt
        - CMAKE_PREFIX_PATH=$QT_PREFIX
        - RELEASE_FILE='DwarfTherapist-*.dmg'
    - os: windows
      env:
        - QT_VERSION=5.12.8
        - QT_ARCH=win64_msvc2017_64
        - CMAKE_GENERATOR="Visual Studio 15 2017"
        - CMAKE_OPTIONS="-A x64"
        - QT_PREFIX="$TRAVIS_BUILD_DIR/Qt/5.12.8/msvc2017_64"
        - CMAKE_PREFIX_PATH=$QT_PREFIX
    - os: windows
      env:
        - QT_VERSION=5.6.3
        - QT_ARCH=win32_msvc2015
        - CMAKE_GENERATOR="Visual Studio 15 2017"
        - CMAKE_OPTIONS="-A Win32 -T v140_xp"
        - QT_PREFIX="$TRAVIS_BUILD_DIR/Qt/5.6.3/msvc2015"
        - CMAKE_PREFIX_PATH=$QT_PREFIX
before_install:
  - ".travis/$TRAVIS_OS_NAME/before_install.sh"
script:
  - cmake ${CMAKE_OPTIONS}
  - |-
      case $TRAVIS_OS_NAME in
        linux)
          ninja -j $(nproc)
          ;;
        osx)
          ninja -j $(sysctl -n hw.ncpu)
          ;;
        windows)
          "/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin/MSBuild.exe" DwarfTherapist.sln //p:Configuration=Release
          ;;
      esac

notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
      - chat.freenode.net#dwarftherapist
    use_notice: true
before_deploy:
  - ".travis/deploy.sh"
  - ".travis/$TRAVIS_OS_NAME/deploy.sh"
deploy:
  provider: releases
  api_key:
    secure: eeglXjGD3+a5eaOPZ6d/DZZEUByfP/7nskbs4NPjrFsUSJgzlJb9dkRgvdFr9W/i/QXMl+nEtqR36YDzxKO9qqoQEWXfRgh75qYjPoDKeeQtZ3/IryArVRa7A8dW2KcV3JBUyp+NOMeAe054sRIR+K4RLSKxZjwdVJUaPH5KpSC4ahsAZTJPHPXREYLUDzOAT5BFqYLOhzcsNniA1vJcxP0fQu25D+lRw/U87xilj3xUJtmTtmwsKHBODtMLuABR8auXIGmcLosUmvsEEIcDiHJo3QsKNDIW/WrCYmVmsvxremJc4Hl4aMbWCfRDXZ6pmJc41ZqswgLoYh4I9+NTl6CYbhST8i9VuoAxmL/gdyoovusFvOvqCPO9mXAmWfxIKoEZeUXNR8DrZrNCpp2OYpI3XA+LRUzjeX7K4xZCBoADQC5I9C8nGncj3jLdfxj4V4qAan4Phk6jrs0y8xiGHiSHOGaXSfXXL5yNArF95U2amzqt1HIh7KjjsJaigr2RwRg/6ircpSVUm4vj/7Vn4jOHncgApfj8n6Bzv65amwcuINCUlJPrA+EM2/LKCj9/ebXuC4rd0n8w9vEUY3I19UoN12Gwz+4BFIZgdNAa+38jFRV2fqgwsb+5c2gqWZZVl112SEhQUpCff5Ce76/7UHFZ5J9SPq8fMuimZVM3zbA=
  file_glob: true
  file: $RELEASE_FILE
  skip_cleanup: true
  on:
    tags: true
