git:
  depth: 1
dist: xenial
sudo: false
language: cpp
matrix:
  include:
    - os: linux
      language: generic
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:beineri/opt-qt-5.12.7-xenial'
          packages:
            - g++-5
            - cmake
            - ninja-build
            - qt512base
            - qt512declarative
            - qt512tools
            - mesa-common-dev
            - libglu1-mesa-dev
      env:
        - COMPILER=g++
        - QT_PREFIX=/opt/qt512
        - APPDIR=DwarfTherapist.AppDir
        - CMAKE_OPTIONS="-DCMAKE_INSTALL_PREFIX=$APPDIR/usr"
        - RELEASE_FILE='DwarfTherapist-*.AppImage'
    - os: osx
      before_install:
        - brew update
        - brew install qt
        - brew outdated cmake || brew upgrade cmake
        - brew install ninja
      env:
        - CXXFLAGS="$CXXFLAGS -mmacosx-version-min=10.9"
        - QT_PREFIX=/usr/local/opt/qt
        - CMAKE_PREFIX_PATH=$QT_PREFIX
        - RELEASE_FILE='DwarfTherapist-*.dmg'
env:
  global:
    - CXXFLAGS="-Wall -Wextra -Werror=all"
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export NPROC=$(nproc);
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then export NPROC=$(sysctl -n hw.ncpu);
    else export NPROC=1; fi
  - cmake -GNinja ${CMAKE_OPTIONS} . && ninja -j $NPROC -k 0
before_deploy:
  - ".travis/deploy.sh"
  - ".travis/$TRAVIS_OS_NAME/deploy.sh"
deploy:
  provider: releases
  api_key:
    secure: rHA/q12iYbGRrwQTak2aAV38I1MHLpvA228KoNA6UcyPtfcLtjrfoKDIGa+Li/0onwUTCjyDgObMdYXrq4A5sznL2ezec6oFHETY6u7xqoEj3ITKqcLUKqQMhQ3p3hwO+Q8u0CpuwmAgDyiSwP7WNnVz0XD3qhu9ZEdM12wG0tp9IoyzayGePwDja12uDlESJtOof5HgVgq6rm2xvVFmQUK8Nzfe8o2mkSLVOjCoWGiP4YJtuE7lPOVF0AfzoxfRCY6UkELTJFaVADWWr8FRq8LPioej2zNToIvRw/5qnIfLRfINj2+Oyg5SVOdyT70J1I/1BH3YrPHJGlAsWiWvgthj8XR8TaLZuj6KTphla4cxgWNo11ozbykFDtW7ssbp8Xobos041YhDT9swkkrT+TQPWHAs3fvlOol9klLBjAeYUYQVgoFHykg9WeHsGLW5uyMCPEj38CM6Ma6X/TyGAPgWo6/QcrTfGk4rd8h3Z9wD2614WY5VZDjftggFqmotgkCybtvPg5EjHlNnq4tZ+RzR5tTzxCbTpCaVcGXKemo1QGn70HMcZdSFBpcqIM8sZISAjsEX3VYnOfCLightlvokl9KnVGRA3w26yem9+hfIWvFfahzF0RYJ8kQIVnqsQj8S5qocpaoT0g8THInDzeYmgsP/shCWgEzfEQ7jJ2I=
  file_glob: true
  file: $RELEASE_FILE
  skip_cleanup: true
  on:
    repo: cvuchener/Dwarf-Therapist
    branch: deploy-test
